-- 기존 공지 83건 (handure.net 에서 이전)

INSERT INTO posts (id,title,author,date,body,pin,images) VALUES (83,'너와두리캠핑장/숙박동 온라인 예약방법','한두레','2025-03-01','휴일엔과의 온라인 예약대행 서비스가 2025년 3월 31일자로 종료됨에 따라
캠핑장 예약은 ''캠핏''이나 ''네이버''를 통해서 예약 가능합니다.(전화예약 가능)
당분간 너와두리 숙박상품은 전화예약만 가능합니다.

너와두리 캠핑장/너와두리 숙박 전화예약 문의 : 010-2309-7620',1,'[]');
INSERT INTO posts (id,title,author,date,body,pin,images) VALUES (82,'6월 23일 치매 예방 교육 진행','한두레','2017-06-27','',0,'["images/notice/notice-82-1.jpg","images/notice/notice-82-2.jpg"]');
INSERT INTO posts (id,title,author,date,body,pin,images) VALUES (81,'6월 6일 삼색떡만들기 체험행사 진행','한두레','2017-06-27','',0,'["images/notice/notice-81-1.jpg","images/notice/notice-81-2.jpg"]');
INSERT INTO posts (id,title,author,date,body,pin,images) VALUES (80,'5월 28일 떡메쳐서 인절미만들기 체험행사 진행','한두레','2017-06-27','',0,'["images/notice/notice-80-1.jpg"]');
INSERT INTO posts (id,title,author,date,body,pin,images) VALUES (79,'5월 14일 삼색떡만들기 체험행사 진행','한두레','2017-06-27','',0,'["images/notice/notice-79-1.jpg"]');
INSERT INTO posts (id,title,author,date,body,pin,images) VALUES (78,'5월 17일-19일 사무장 중급교육 실시','한두레','2017-05-25','2박 3일 동안 사무장 중급 2단계 교육이 있었습니다,21명의 사무장님들께서 초급에 이어 두번째 교육을 참여해주셨습니다.',0,'["images/notice/notice-78-1.jpg","images/notice/notice-78-2.jpg","images/notice/notice-78-3.jpg","images/notice/notice-78-4.jpg"]');
INSERT INTO posts (id,title,author,date,body,pin,images) VALUES (77,'옥천 향수 테마관광열차 한두레농촌체험마을 다녀가다','한두레','2017-05-24','2016년 농촌체험휴양마을 "으뜸촌"으로 선정이 되면서 17년 진행된 옥천향수테마관광열차 한두레마을을 다녀가셨습니다,5월14일 첫 스타트를 시작으로 진행이 됩니다.일요일 80명 체험객분들께서 알록달록삼색떡만들기체험을 하시고 맛있게 준비한 점심식사를 하시고 오래 머무르고 싶다시며 떠나셧습니다.찾아주신 분들께 모두 감사드립니다.앞으로 여러번 진행이 될 예정입니다... 농산물수확체험도 진행예정이오니 많은 참여와 관심 부탁드립니다.',0,'["images/notice/notice-77-1.jpg","images/notice/notice-77-2.jpg","images/notice/notice-77-3.jpg","images/notice/notice-77-4.jpg","images/notice/notice-77-5.jpg","images/notice/notice-77-6.jpg","images/notice/notice-77-7.jpg","images/notice/notice-77-8.jpg","images/notice/notice-77-9.jpg","images/notice/notice-77-10.jpg"]');
INSERT INTO posts (id,title,author,date,body,pin,images) VALUES (76,'5월 5일 어린이날 무료체험행사 진행','한두레','2017-05-24','5월 5일 어린이날을 맞이하여 캠핑을 오신분들 사이트를 찾아다니며 가위바위보 게임을 진행하고 알록달록삼색떡만들기 체험을 진행하였습니다.일요일 오전 보물찾기를 하기 위하여 아무도 모르고 보물도 숨기러 다니고찾은 아이들은 아이스크림을 무료로 나눠주는 행사까지 하였습니다.체험에서 잘하신분들께는 캠핑장 무료 이용권도 드리는 혜택이 있었습니다.내년부터는 더욱 많은 행사를 계획하여 추진하려 합니다.항상 너와두리캠핑장을 찾아주시는 가족분들께 감사드립니다.',0,'["images/notice/notice-76-1.jpg","images/notice/notice-76-2.jpg","images/notice/notice-76-3.jpg","images/notice/notice-76-4.jpg","images/notice/notice-76-5.jpg","images/notice/notice-76-6.jpg","images/notice/notice-76-7.jpg","images/notice/notice-76-8.jpg"]');
INSERT INTO posts (id,title,author,date,body,pin,images) VALUES (75,'유로카라반 정기모임','한두레','2017-05-24','4월 28일 - 30일 2박3일 유로카라반 정기모임 진행계란꾸러미만들기 짚풀공예체험도 진행하고 각종 행사 진행어린이를 위한 공연 및 가수 초청과 불꽃놀이도 진행하였습니다.',0,'["images/notice/notice-75-1.jpg","images/notice/notice-75-2.jpg","images/notice/notice-75-3.jpg","images/notice/notice-75-4.jpg","images/notice/notice-75-5.jpg"]');
INSERT INTO posts (id,title,author,date,body,pin,images) VALUES (74,'칙칙폭폭 테마관광열차, 한두레권역으로 간다','한두레','2017-03-11','- 목 적  -* 청정지역 옥천군이 보유한 다양한 체험형 관광상품개발을 적극활용하여 옥천군 내의 지역경제 및 관광활성화 방안수립 필요* 체험형 관광자원의 발굴로 관광의 질과 다양성 추구.2017년 4월부터 11월까지 옥천 향수 테마관광열차 운행',0,'["images/notice/notice-74-1.jpg"]');
INSERT INTO posts (id,title,author,date,body,pin,images) VALUES (73,'옥천군 일반농산어촌개발사업 준비지구 주민역량 강화교육 실시','한두레','2016-12-06','2016년 12월 6일 9시~19시옥천군 일반농산어촌개발사업 준비지구 주민역량 강화교육',0,'["images/notice/notice-73-1.jpg","images/notice/notice-73-2.jpg","images/notice/notice-73-3.jpg"]');
INSERT INTO posts (id,title,author,date,body,pin,images) VALUES (72,'F&F 트레일러 정기모임 공지','한두레','2016-12-05','2016년 12월 F&F트레일러 정기모임 공지12월 23일-25일 크리스마스 캠핑으로 진행됩니다.2016년을 마무리하는 마지막주 마지막 너와두리에서의 행사입니다,많은 회원분들께서 참석하시어 즐거운 추억 만드셨으면 합니다.날씨가 더 추워지기 시작을 하면 너와두리 캠핑장에서는 썰매장을만들고자 합니다.. 아무쪼록 썰매장이 만들어지게되면 다시한번 공지나 카카오스토리에 남기도록 하겠습니다.많은 회원분들의 참여 부탁드립니다... 감사합니다.',0,'[]');
INSERT INTO posts (id,title,author,date,body,pin,images) VALUES (71,'제8회 너와두리 한마음축제를 성황리 마치며....','한두레','2016-12-04','지난 11월 19일 한두레마을 축제제8회 너와두리한마음축제가 도농교류복합센터에서 열렸습니다.군수님을 비롯하여 많으신분들이 찾아주셔서 감사드립니다.윷놀이대회와 점심을 맛있게 드시고 노래자랑 및 경품 추첨이 진행되었습니다.가수분들도 초빙하여 즐거운 시간도 되었습니다.캠핑을 오신분들께도 점심식사를 대접해드리고 경품추첨을 통해직접 농사를 지은 고구마를 1박스씩 드리는 행사도 진행하였습니다내년에도 많은 준비를 하여 진행할 예정이오니 캠핑객분들께서도 많이 참석해주시면 감사하겠습니다.항상 저희 너와두리 캠핑장을 이용해주시는 고객분들께 진심으로 감사드립니다.',0,'["images/notice/notice-71-1.jpg","images/notice/notice-71-2.jpg","images/notice/notice-71-3.jpg","images/notice/notice-71-4.jpg","images/notice/notice-71-5.jpg","images/notice/notice-71-6.jpg"]');
INSERT INTO posts (id,title,author,date,body,pin,images) VALUES (70,'11월 28일 현장포럼 진행','한두레','2016-12-04','한두레권역 1회차 농촌현장포럼11월 28일 13시-19시 마을 주민 35명이 참석해주시고 열정적으로 교육에 참여하시고 좋은 의견을 말씀해주셔서 마을운영에 적극 반영이 되도록 하겠습니다.',0,'["images/notice/notice-70-1.jpg","images/notice/notice-70-2.jpg","images/notice/notice-70-3.jpg","images/notice/notice-70-4.jpg"]');
